### ISSUE TITLE
Having trouble finding SublimeLinter in package control

### ISSUE THREAD

**Issue by BenRacicot** [SublimeLinter/docs#13]
Hello! Thank you for your work on this plugin. I'd love to try it out but can't seem to find it within Sublime Text's Package Control. SublimeLinter does not appear on any "linter" based searches. Am I missing something obvious?

Thanks.

**Comment by skj3gg** [comment]
@BenRacicot, has this issue been resolved?

**Comment by BenRacicot** [comment]
I couldn't find it so I had to call it quits. :(

**Comment by scionweb** [comment]
Package Control will not display sublimelinter for me either. I am working in ST3 Build 3065 64-bit on Win7 64-bit. I saw the google group thread but nothing there helped.

ST3 is a recent install so I can test it out, so I do still have ST2 installed. I have never previously installed or used sublimelinter.

Thanks for any help you can give.

**Comment by skj3gg** [comment]
This should be fixed now for everyone! Both ST2 and ST3 users should be able to find SublimeLinter in Package Control
